---
- name: Installing Nextcloud on CentOS
  hosts: tag_Name_lookatme
  remote_user: centos
  become: true
  vars:
    - db_name: nextcloud
    - nc_dbuser: user
    - nc_dbpassword: passd234

  tasks:

  - name: Add Webtatic repo
    yum:
      name: "https://mirror.webtatic.com/yum/el7/webtatic-release.rpm"
      state: present

  - name: Add epel repo
    yum:
      name: epel-release
      state: present

  - name: Install Prerequisites
    yum:
      enablerepo: centosplus
      update_cache: yes
      name: '{{ item }}'
      state: latest
    with_items:
      - wget
      - bzip2
      - httpd
      - mariadb-server
      - MySQL-python
      - php70w
      - php70w-fpm
      - mod_php

  - name: extract installer
    unarchive:
      src: https://download.nextcloud.com/server/releases/nextcloud-12.0.2.tar.bz2
      dest: /var/www/html/
      remote_src: True
      owner: apache
      group: apache

  - name: Create datadir
    file:
      dest: /var/www/html/nextcloud/data
      owner: apache
      group: apache
      mode: 0775
      state: directory

#  - name: Change Owner to Web Server
#    file:
#      dest: /var/www/html/nextcloud/
#      owner: apache
#      group: apache
#      state: directory
#      recurse: yes

  - name: Start DB Before Creating DBUser
    service:
      name: mariadb
      state: started

  - name: Create Database
    mysql_db:
      name: nextcloud
      state: present

  - name: Create NextCloud database user
    mysql_user:
      name: 'user'
      password: 'passd234'
      priv: 'nextcloud.*:ALL'
      host: 'localhost'
      state: present

  - name: Complete DB and DBUser Creation
    service:
      name: mariadb
      state: restarted

  - name: Nearly Done! Checking Setup...
    file:
      path: /var/www/html/nextcloud/config
      owner: apache
      group: apache
      mode: 0775
      state: directory

  - name: Nearly Done! Checking Setup...
    file:
      path: /var/www/html/nextcloud/apps
      owner: apache
      group: apache
      mode: 0775
      state: directory

  - name: Set SELinux to permissive before turning off
    selinux:
      policy: targeted
      state: permissive

  - name: Restart Web Services
    service:
      name: httpd
      state: restarted

  - name: Turn off SELinux
    selinux:
      state: disabled

  - name: restart mariadb
    service:
      name: mariadb
      state: restarted

  - name: restart httpd
    service:
      name: httpd
      state: restarted

  handlers:
  - name: restart mariadb
    service:
      name: mariadb
      state: restarted

  - name: restart httpd
    service:
      name: httpd
      state: restarted
